### ISSUE TITLE
Dagger2 example

### ISSUE THREAD

**Issue by jeromevdl** [aws-samples/serverless-java-frameworks-samples#8]
It would be great to have a Dagger2 example. [Dagger2](https://dagger.dev/) is not really comparable to Spring or Micronaut... as it only provides dependency injection. It's very lightweight (compared to Spring), doesn't use reflection (compile-time vs runtime) and is widely used in the Android world. It can play nicely with GraalV (everything is static). I think it's also interesting to compare performances with other fwks.

Let me know if that makes sense to have it here and I can work on it and provide a PR (same architecture, same load tests, ...).

**Comment by dmahapatro** [comment]
@jeromevdl It does make sense. However, just wondering will it make more sense if it is separate repo like I had for [Groovy](https://github.com/aws-samples/serverless-groovy-demo) and Kotlin.

**Comment by dmahapatro** [comment]
@jeromevdl I believe you are correct. Let's add Dagger2 in this repo. Let me know when you have the PR.
